blueprint:
  name: Scene controller button sync
  description: Toggle and sync the button LED of a Z-Wave scene controller to a switch or light. Built for Zooz ZEN32.
  domain: automation
  input:
    zooz_switch:
      name: Zooz Switch
      description: List of available Zooz ZEN32 switches.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN32
    target_switch:
      name: Light or Switch
      description: The light or switch to link to button
      selector:
        entity:
          domain: 
            - light
            - switch
    scene_button:
      name: Scene Button
      description: The button to link to light where button 1 is the big button.
      selector:
        entity:
          include_entities: {{ device_entities(!input 'zooz_switch') }}
          filter:
            domain: switch
            integration: zwave_js
            device_class: switch
            

mode: single
max_exceeded: silent
variables:
  controller_id: !input 'zooz_switch'
  switch_id: !input 'target_switch'
  button_id: !input 'scene_button'
  
trigger:
  - platform: state
    entity_id: !input 'target_switch'

action:
- choose:
  - conditions: '{{ is_state(switch_id, ''off'') }}' # target switch is off
    sequence:
      - parallel:
          - service: switch.turn_off
            target:
              entity_id: button_id
  - conditions: '{{ is_state(switch_id, ''on'') }}' # target switch is on
    sequence:
      - parallel:
          - service: switch.turn_on
            target:
              entity_id: button_id
