blueprint:
  name: Scene controller button sync
  description: Toggle and sync the button LED of a Z-Wave scene controller to a switch or light. Built for Zooz ZEN32.
  domain: automation
  input:
    zooz_switch:
      name: Zooz Switch
      description: List of available Zooz ZEN32 switches.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN32
    target_switch:
      name: Light or Switch
      description: The light or switch to link to button
      selector:
        entity:
          domain: 
            - light
            - switch
    scene_button:
      name: Scene Button
      description: The button to link to light
      selector:
        select:
          mode: dropdown
          options:
            - label: Scene 5 (Big Button)
              value: '0' # param 1 for on/off, param 6 for color
            - label: Scene 1 (Top Left)
              value: '1' # param 2 for on/off, param 7 for color
            - label: Scene 2 (Top Right)
              value: '2' # param 3 for on/off, param 8 for color
            - label: Scene 3 (Bottom Left)
              value: '3' # param 4 for on/off, param 9 for color
            - label: Scene 4 (Bottom Right)
              value: '4' # param 5 for on/off, param 10 for colo

mode: single
max_exceeded: silent
variables:
  controller_id: !input 'zooz_switch'
  switch_id: !input 'target_switch'
  button_id: !input 'scene_button'
  
trigger:
  - platform: state
    entity_id: !input 'target_switch'

action:
- choose:
  - conditions: '{{ is_state(switch_id, ''off'') }}' # target switch is off
    sequence:
      - parallel:
          - service: switch.turn_off
            target:
              entity_id: switch.lr_scene_controller_button_{{ button_id | int + 1 }}_indication_binary
  - conditions: '{{ is_state(switch_id, ''on'') }}' # target switch is on
    sequence:
      - parallel:
          - service: switch.turn_on
            target:
              entity_id: switch.lr_scene_controller_button_{{ button_id | int + 1 }}_indication_binary
